### ISSUE TITLE
Cannot build application

### ISSUE THREAD

**Issue by mauleyzaola** [Email-Dashboard/Email-Dashboard#12]
I followed the README instructions to make it work, however that this point there was a failure.
```
Email-Dashboard$ docker-compose run web rake db:migrate
```
Result
```
Creating network "email-dashboard_default" with the default driver
Creating volume "email-dashboard_datadrive" with default driver
Pulling redis (redis:alpine)...
alpine: Pulling from library/redis
4fe2ade4980c: Already exists
fb758dc2e038: Pull complete
989f7b0c858b: Pull complete
d5318f13abaa: Pull complete
3521559474dd: Pull complete
af5d048338ef: Pull complete
Digest: sha256:fc78e96c8036b6fa69ce8d4e811ba84b9278e772047a93fb6d5549de4ddecc32
Status: Downloaded newer image for redis:alpine
Creating email-dashboard_redis_1 ... error
Creating email-dashboard_db_1    ...

ERROR: for email-dashboard_redis_1  Cannot start service redis: b'Mounts denied: \r\nThe path /datadrive/redis\r\nis not shared from OS X and is not known to Docker.\r\nYou can configure shared paths from Docker -> Preferences... -> File Sharing.\r\nSee https://docs.docCreating email-dashboard_db_1    ... error

ERROR: for email-dashboard_db_1  Cannot start service db: b'Mounts denied: \r\nThe path /datadrive/mysql\r\nis not shared from OS X and is not known to Docker.\r\nYou can configure shared paths from Docker -> Preferences... -> File Sharing.\r\nSee https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.\r\n.'

ERROR: for redis  Cannot start service redis: b'Mounts denied: \r\nThe path /datadrive/redis\r\nis not shared from OS X and is not known to Docker.\r\nYou can configure shared paths from Docker -> Preferences... -> File Sharing.\r\nSee https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.\r\n.'

ERROR: for db  Cannot start service db: b'Mounts denied: \r\nThe path /datadrive/mysql\r\nis not shared from OS X and is not known to Docker.\r\nYou can configure shared paths from Docker -> Preferences... -> File Sharing.\r\nSee https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.\r\n.'
ERROR: Encountered errors while bringing up the project.
```

This is how I created the data directories
```
sudo mkdir /datadrive
sudo chown -R mau /datadrive/
mkdir -p /datadrive/mysql && mkdir -p /datadrive/data/redis
```

OS: MacOS High Sierra
Version: 10.13.6

**Comment by sadikay** [comment]
@mauleyzaola Actually the config was production ubuntu config. I just updated it to works in mac as well.
Can you pull the master and try again ?

Don't forget to run: `mkdir -p ~/datadrive/mysql && mkdir -p ~/datadrive/data/redis`

**Comment by mauleyzaola** [comment]
![image](https://user-images.githubusercontent.com/1648558/45626106-3ab8aa00-ba54-11e8-8c84-1f2d90e78fe2.png)

😄

**Comment by mauleyzaola** [comment]
I can see you've already updated the README to point to my home instead of the `/` path. Thanks will give it another try.

**Comment by mauleyzaola** [comment]
Not there yet. Have you guys tested this actually works on a Mac environment?
```
Email-Dashboard$ docker-compose run web rake db:migrate
```
Result
```
Creating volume "email-dashboard_datadrive" with default driver
Pulling db (mysql:5.7)...
5.7: Pulling from library/mysql
802b00ed6f79: Pull complete
30f19a05b898: Pull complete
3e43303be5e9: Pull complete
94b281824ae2: Pull complete
51eb397095b1: Pull complete
54567da6fdf0: Pull complete
bc57ddb85cce: Pull complete
c7c0a9c25d8a: Pull complete
cce6c47ac3fc: Pull complete
499b9c7376c8: Pull complete
6c5e08e005ea: Pull complete
Digest: sha256:1d8f471c7e2929ee1e2bfbc1d16fc8afccd2e070afed24805487e726ce601a6d
Status: Downloaded newer image for mysql:5.7
Pulling redis (redis:alpine)...
alpine: Pulling from library/redis
4fe2ade4980c: Pull complete
fb758dc2e038: Pull complete
989f7b0c858b: Pull complete
d5318f13abaa: Pull complete
3521559474dd: Pull complete
af5d048338ef: Pull complete
Digest: sha256:fc78e96c8036b6fa69ce8d4e811ba84b9278e772047a93fb6d5549de4ddecc32
Status: Downloaded newer image for redis:alpine
Creating email-dashboard_db_1    ... done
Creating email-dashboard_redis_1 ... done
rake aborted!
Mysql2::Error: Can't connect to MySQL server on 'db' (113)
/usr/local/bundle/gems/mysql2-0.4.10/lib/mysql2/client.rb:89:in `connect'
/usr/local/bundle/gems/mysql2-0.4.10/lib/mysql2/client.rb:89:in `initialize'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_adapters/mysql2_adapter.rb:21:in `new'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_adapters/mysql2_adapter.rb:21:in `mysql2_connection'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:759:in `new_connection'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:803:in `checkout_new_connection'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:782:in `try_to_checkout_new_connection'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:743:in `acquire_connection'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:500:in `checkout'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:374:in `connection'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_handling.rb:116:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_handling.rb:88:in `connection'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/schema_migration.rb:20:in `table_exists?'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/schema_migration.rb:24:in `create_table'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/migration.rb:1125:in `initialize'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/migration.rb:1007:in `new'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/migration.rb:1007:in `up'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/migration.rb:985:in `migrate'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/bugsnag-6.2.0/lib/bugsnag/integrations/rake.rb:16:in `execute_with_bugsnag'
/usr/local/bundle/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
Email-Dashboard$ docker-compose up
Pulling nginx-proxy (jwilder/nginx-proxy:)...
latest: Pulling from jwilder/nginx-proxy
be8881be8156: Pull complete
b4babd36efe5: Pull complete
f4eba7658e18: Pull complete
fc141716ac64: Pull complete
87b964c68304: Pull complete
d07092114f4c: Pull complete
5092b1e0c1da: Pull complete
d90a3596290d: Pull complete
5ca9f664a671: Pull complete
eb9b93208683: Pull complete
Digest: sha256:e869d7aea7c5d4bae95c42267d22c913c46afd2dd8113ebe2a24423926ba1fff
Status: Downloaded newer image for jwilder/nginx-proxy:latest
email-dashboard_redis_1 is up-to-date
email-dashboard_db_1 is up-to-date
Creating email-dashboard_nginx-proxy_1 ... done
Creating email-dashboard_web_1         ... done

ERROR: for api  Container "2a365f400560" is unhealthy.
ERROR: Encountered errors while bringing up the project.
```
Contents of `.env` file
```
SECRET_KEY_BASE=3ed1a403c0556528640b6eefe5c0a692fd88db7c92e8f69cacade6a6cf96fecc1e60c2b1aa2283471564fb2c5f0a3be08b8f0ded78803c38f37257596420bc7a
GIN_MODE=release
MYSQL_ROOT_PASSWORD=
MYSQL_USER=root
MYSQL_PASSWORD=
APP_DOMAIN=mauleyzaola.com
```

**Comment by sadikay** [comment]
Alright, I have to write different doc for osx.

**Comment by sadikay** [comment]
@mauleyzaola the docs just updated and tested on osx. Thanks for the issue.
Now you just have to follow this:
* Clean old runs:
```
sudo docker stop $(sudo docker ps -aq)
sudo docker rm $(sudo docker ps -aq)
```
* Pull the repo again
* Enable mocOS config in `docker-compose.yml`
* Finally run:
```
  sudo docker-compose build
  sudo docker-compose run web rake db:migrate
  sudo docker-compose up -d
```
